---
version: 2.1
orbs:
  terraform: circleci/terraform@3.6.0
workflows:
  deploy_infra:
    jobs:
      - terraform/validate:
          checkout: true
          context: terraform

      - terraform/plan:
          checkout: true
          context: terraform
          persist-worksapce: true
          requires:
            - terraform/validate
            
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only:
                main
          requires:
            - terraform/plan
  